version: '3'

services:

  mongodb:
    image: mongo
    container_name: mongoDb
    ports: 
      -27017:27017
    environment:
      -MONGO-INITDB_ROOT_USERNAME=admin
      -MONGO-INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    container_name: mongoExpress
    port:
      -8080:8080
    environment:
      -ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      -ME_CONFIG_MONGODB_ADMINPASSWORD=password

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      -3000:3000
    volumes:
      -grafana-storage: var/lib/grafana
  
  volumes:
    grafana-storage: {}
